In [46]:
import pandas as pd
from io import StringIO
import csv
import numpy as np
from scipy.linalg import solve
import re

In [26]:
def make_POSCAR(iteration,outcar="OUTCAR",headings_file="POSCAR",fileout="POSCAR_"):
    
    # read in data from outcar and extract list of atomic positions at a given ionic step
    data = open(outcar,'r').read()
    data = data.split(str(iteration)+"(",1)[-1].split("total drift,1")[-1].split("total drift")[0].split("Angst)")[-1]
    df = pd.read_csv(StringIO(data),delimiter="\n",names="r",skiprows=2)
    positions = [df.r[i].split()[:3] for i in range(df.r.count()-1)]
    position_floats = np.array([[float(value) for value in vector] for vector in positions])
    
    # read the cell data from the POSCAR
#    i=0
#    cell_matrix = np.zeros(shape=(3,3))
#    with open(headings_file,'r') as filein:
#        for line in filein:
#            if isfloat(line.strip()):
#                scaling = float(line.strip())

#            elif ([isfloat(item) for item in line.strip().split()] == [True]*len(line.strip().split())) & (i<3):
#                cell_vector=[float(value) for value in (line.strip().split())]
#                cell_matrix[i]=cell_vector
#                i+=1
                
    # read the cell data from the OUTCAR
    cell_matrix = np.zeros(shape=(3,3))
    cell_matrix[0]=re.search(r'A1 = \((\s+.*\s+)A2',data).group(1).split()
    cell_matrix[1]=re.search(r'A2 = \((\s+.*\s+)A3',data).group(1).split()
    cell_matrix[2]=
    
    # use cell data to convert positions in angstrom to fractional coordinates
    position_fractional = []
    for position in position_floats:
        position_fractional.append(list(solve(cell_matrix,position)))
    
    # read the POSCAR heading information and copy to new fileout
    i=0
    cell_matrix = np.zeros(shape=(3,3))
    with open(headings_file,'r') as filein, open(fileout+str(iteration),'w') as fileout:
        copy = True
        for line in filein:                
            if line.strip() == "Direct":
                fileout.write(line)
                copy == False
                break
            elif copy:
                fileout.write(line)
        # write the atomic positions to fileout
        for position in position_fractional:
            fileout.write(str(position[0])+"     "+str(position[1])+"     "+str(position[2])+"\n")


def isfloat(value):
  try:
    float(value)
    return True
  except ValueError:
    return False

In [30]:
make_POSCAR(1,outcar="/Users/lucydot/data/235/192_atoms/negative_int/Q-E-analysis/OUTCAR",headings_file="/Users/lucydot/data/235/192_atoms/negative_int/Q-E-analysis/POSCAR")

In [5]:
position_floats[1]

array([12.61601,  9.1274 ,  2.88161])

In [6]:
cell_matrix

array([[17.71322441,  0.        ,  0.        ],
       [-0.14269317, 17.71125915,  0.        ],
       [ 0.19681646, -0.19647375, 12.75438333]])

In [7]:
x=solve(cell_matrix,position_floats[1])
np.dot(cell_matrix,x)

array([12.61601,  9.1274 ,  2.88161])

In [13]:
position_fractional = []
for position in position_floats:
    position_fractional.append(list(solve(cell_matrix,position)))

In [18]:
for position in position_fractional:
        print (str(position[0])+"     "+str(position[1]))

0.2105325328393707     0.01796944823085057
0.7122367846345015     0.5210827330924301
0.7305180411966273     0.5254973605212552
0.9783741004962307     0.7915658160077224
0.9746175851122401     0.7735283616186126
0.23525812710937943     0.0185492022352028
0.4806679914647642     0.29377121046006704
0.4815294946922919     0.2685354513536062
0.9795286051491103     0.284879352655743
0.9758754024064289     0.2748562771884527
0.2176554595901687     0.5191939132991377
0.22930551241013128     0.5234704236432939
0.4494195870434739     0.751452451393669
0.4721613527803682     0.7643038863317028
0.7524445968020995     0.05060615379262987
0.7394006701493938     0.027697490111105418
0.25033443359111524     0.967067946383373
0.7705282608808474     0.47212053355766337
0.7872361167253323     0.47173852214690964
0.028228626725323096     0.7257071856709737
0.02859219689473848     0.7097253676292573
0.28844155538542965     0.967371573920179
0.531563298783298     0.24633372562713388
0.5338294022926666     0

In [20]:
with open("test",'w') as fileout:
    for position in position_fractional:
        fileout.write(str(position[0])+"     "+str(position[1])+"     "+str(position[2])+"\n")

In [64]:
outcar="/Users/lucydot/data/235/192_atoms/negative_int/Q-E-analysis/OUTCAR"
data = open(outcar,'r').read()
#data = data.split("1(",1)[-1].split("total drift,1")[-1].split("total drift")[0].split("Angst)")[-1]

In [139]:
A1=re.search(r'A1 = \(\s+(\d+\.\d+).*\n.*A2',data).group(1).split()
A1[0]

AttributeError: 'NoneType' object has no attribute 'group'

In [163]:
A2=re.search(r'A2 = \(\s+(\d+.*\d+)\)\s+A3',data).group(1).split()
A21=float(re.search(r'(\d+\.\d+),',A2[0]).group(1))
A22=float(re.search(r'(\d+\.\d+),',A2[1]).group(1))
A23=float(A2[2])



In [125]:
A3=re.search(r'A3 = \((\s+.*\s+)Analysis',data).group(1).split()
A3

['-0.1968164558,', '0.1964737486,', '-12.7543833321)']

In [119]:
A1.split()

['-0.1426931695,', '17.7112591497,', '0.0000000000)']

In [164]:
A21

17.5705312415

In [165]:
A22

17.7112591497

In [166]:
A23

0.0